# Use an official PHP image as the base image
FROM php:apache

# Set the working directory within the container
WORKDIR /var/www/html

# Copy the entire PHP project into the container
COPY lifestyleStore/ .

# Expose port 80 for the Apache web server
EXPOSE 80